/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SpeakerRouteImport } from './routes/speaker'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated.fleet'
import { Route as AuthenticatedFlightAlertsRouteImport } from './routes/_authenticated.flight-alerts'
import { Route as AuthenticatedGateRouteImport } from './routes/_authenticated.gate'
import { Route as AuthenticatedHotelsRouteImport } from './routes/_authenticated.hotels'
import { Route as AuthenticatedInviteesRouteImport } from './routes/_authenticated.invitees'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated.movements'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated.operations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated.sessions'
import { Route as AuthenticatedSessionsLiveRouteImport } from './routes/_authenticated.sessions-live'
import { Route as AuthenticatedSessionsMapRouteImport } from './routes/_authenticated.sessions-map'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSheetsRouteImport } from './routes/_authenticated.sheets'
import { Route as AuthenticatedSpeakersRouteImport } from './routes/_authenticated.speakers'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated.tickets'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicSheetsTableRouteImport } from './routes/api/public/sheets.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakerRoute = SpeakerRouteImport.update({
  id: '/speaker',
  path: '/speaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlightAlertsRoute =
  AuthenticatedFlightAlertsRouteImport.update({
    id: '/flight-alerts',
    path: '/flight-alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGateRoute = AuthenticatedGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHotelsRoute = AuthenticatedHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInviteesRoute = AuthenticatedInviteesRouteImport.update({
  id: '/invitees',
  path: '/invitees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsLiveRoute =
  AuthenticatedSessionsLiveRouteImport.update({
    id: '/sessions-live',
    path: '/sessions-live',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsMapRoute =
  AuthenticatedSessionsMapRouteImport.update({
    id: '/sessions-map',
    path: '/sessions-map',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSheetsRoute = AuthenticatedSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpeakersRoute = AuthenticatedSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetsTableRoute = ApiPublicSheetsTableRouteImport.update({
  id: '/api/public/sheets/$table',
  path: '/api/public/sheets/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/speaker': typeof SpeakerRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/flight-alerts': typeof AuthenticatedFlightAlertsRoute
  '/gate': typeof AuthenticatedGateRoute
  '/hotels': typeof AuthenticatedHotelsRoute
  '/invitees': typeof AuthenticatedInviteesRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/sessions-live': typeof AuthenticatedSessionsLiveRoute
  '/sessions-map': typeof AuthenticatedSessionsMapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/speakers': typeof AuthenticatedSpeakersRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sheets/$table': typeof ApiPublicSheetsTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/speaker': typeof SpeakerRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/flight-alerts': typeof AuthenticatedFlightAlertsRoute
  '/gate': typeof AuthenticatedGateRoute
  '/hotels': typeof AuthenticatedHotelsRoute
  '/invitees': typeof AuthenticatedInviteesRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/sessions-live': typeof AuthenticatedSessionsLiveRoute
  '/sessions-map': typeof AuthenticatedSessionsMapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/speakers': typeof AuthenticatedSpeakersRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sheets/$table': typeof ApiPublicSheetsTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/speaker': typeof SpeakerRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/flight-alerts': typeof AuthenticatedFlightAlertsRoute
  '/_authenticated/gate': typeof AuthenticatedGateRoute
  '/_authenticated/hotels': typeof AuthenticatedHotelsRoute
  '/_authenticated/invitees': typeof AuthenticatedInviteesRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/sessions-live': typeof AuthenticatedSessionsLiveRoute
  '/_authenticated/sessions-map': typeof AuthenticatedSessionsMapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets': typeof AuthenticatedSheetsRoute
  '/_authenticated/speakers': typeof AuthenticatedSpeakersRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sheets/$table': typeof ApiPublicSheetsTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/speaker'
    | '/activity'
    | '/calendar'
    | '/dashboard'
    | '/fleet'
    | '/flight-alerts'
    | '/gate'
    | '/hotels'
    | '/invitees'
    | '/movements'
    | '/notifications'
    | '/operations'
    | '/reports'
    | '/sessions'
    | '/sessions-live'
    | '/sessions-map'
    | '/settings'
    | '/sheets'
    | '/speakers'
    | '/tickets'
    | '/users'
    | '/api/public/health'
    | '/api/public/sheets/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/speaker'
    | '/activity'
    | '/calendar'
    | '/dashboard'
    | '/fleet'
    | '/flight-alerts'
    | '/gate'
    | '/hotels'
    | '/invitees'
    | '/movements'
    | '/notifications'
    | '/operations'
    | '/reports'
    | '/sessions'
    | '/sessions-live'
    | '/sessions-map'
    | '/settings'
    | '/sheets'
    | '/speakers'
    | '/tickets'
    | '/users'
    | '/api/public/health'
    | '/api/public/sheets/$table'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/speaker'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/fleet'
    | '/_authenticated/flight-alerts'
    | '/_authenticated/gate'
    | '/_authenticated/hotels'
    | '/_authenticated/invitees'
    | '/_authenticated/movements'
    | '/_authenticated/notifications'
    | '/_authenticated/operations'
    | '/_authenticated/reports'
    | '/_authenticated/sessions'
    | '/_authenticated/sessions-live'
    | '/_authenticated/sessions-map'
    | '/_authenticated/settings'
    | '/_authenticated/sheets'
    | '/_authenticated/speakers'
    | '/_authenticated/tickets'
    | '/_authenticated/users'
    | '/api/public/health'
    | '/api/public/sheets/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SpeakerRoute: typeof SpeakerRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSheetsTableRoute: typeof ApiPublicSheetsTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaker': {
      id: '/speaker'
      path: '/speaker'
      fullPath: '/speaker'
      preLoaderRoute: typeof SpeakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flight-alerts': {
      id: '/_authenticated/flight-alerts'
      path: '/flight-alerts'
      fullPath: '/flight-alerts'
      preLoaderRoute: typeof AuthenticatedFlightAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gate': {
      id: '/_authenticated/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AuthenticatedGateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hotels': {
      id: '/_authenticated/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AuthenticatedHotelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitees': {
      id: '/_authenticated/invitees'
      path: '/invitees'
      fullPath: '/invitees'
      preLoaderRoute: typeof AuthenticatedInviteesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions-live': {
      id: '/_authenticated/sessions-live'
      path: '/sessions-live'
      fullPath: '/sessions-live'
      preLoaderRoute: typeof AuthenticatedSessionsLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions-map': {
      id: '/_authenticated/sessions-map'
      path: '/sessions-map'
      fullPath: '/sessions-map'
      preLoaderRoute: typeof AuthenticatedSessionsMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sheets': {
      id: '/_authenticated/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof AuthenticatedSheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/speakers': {
      id: '/_authenticated/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AuthenticatedSpeakersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheets/$table': {
      id: '/api/public/sheets/$table'
      path: '/api/public/sheets/$table'
      fullPath: '/api/public/sheets/$table'
      preLoaderRoute: typeof ApiPublicSheetsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedFlightAlertsRoute: typeof AuthenticatedFlightAlertsRoute
  AuthenticatedGateRoute: typeof AuthenticatedGateRoute
  AuthenticatedHotelsRoute: typeof AuthenticatedHotelsRoute
  AuthenticatedInviteesRoute: typeof AuthenticatedInviteesRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSessionsLiveRoute: typeof AuthenticatedSessionsLiveRoute
  AuthenticatedSessionsMapRoute: typeof AuthenticatedSessionsMapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsRoute: typeof AuthenticatedSheetsRoute
  AuthenticatedSpeakersRoute: typeof AuthenticatedSpeakersRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedFlightAlertsRoute: AuthenticatedFlightAlertsRoute,
  AuthenticatedGateRoute: AuthenticatedGateRoute,
  AuthenticatedHotelsRoute: AuthenticatedHotelsRoute,
  AuthenticatedInviteesRoute: AuthenticatedInviteesRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSessionsLiveRoute: AuthenticatedSessionsLiveRoute,
  AuthenticatedSessionsMapRoute: AuthenticatedSessionsMapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsRoute: AuthenticatedSheetsRoute,
  AuthenticatedSpeakersRoute: AuthenticatedSpeakersRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SpeakerRoute: SpeakerRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSheetsTableRoute: ApiPublicSheetsTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
